plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.asciidoctor.jvm.convert' version '4.0.5'
}

group = 'ru.pancoManco'
version = '0.0.1-SNAPSHOT'
description = 'ToDoAppSevenProject'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
}

ext {
    mapstructVersion = '1.6.3'
    resilience4jVersion='2.4.0'
}

dependencies {
    // =========================
    // Web / REST API
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // =========================
    // Security / JWT / OAuth2 Client
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'

    // =========================
    // Database / JPA / Migrations
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    runtimeOnly 'org.postgresql:postgresql'

    // =========================
    // Mail
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // =========================
    // Resilience4j (Rate Limiter)
    // =========================
    implementation "io.github.resilience4j:resilience4j-spring-boot4:${resilience4jVersion}"

    // =========================
    // Mapping
    // =========================
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    // =========================
    // Lombok
    // =========================
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // =========================
    // Development
    // =========================
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // =========================
    // Tests: Core
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // =========================
    // Tests: Database / Liquibase
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'

    // =========================
    // Tests: Security / OAuth2 / JWT
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'

    // =========================
    // Tests: Mail
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-mail-test'

    // =========================
    // Tests: Testcontainers
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-postgresql'

    // =========================
    // Tests: Lombok
    // =========================
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

}

tasks.named('test') {
    useJUnitPlatform()
}

