server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    jwt:
      issuer: ${JWT_ISSUER:toDoApplication}
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8081}/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - ${FRONTEND_ORIGIN:http://localhost:5173}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                  - X-Request-Id
                  - Set-Cookie
                allowCredentials: true
                maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
          routes:
            # ========== AUTH-SERVICE ==========
            - id: auth-register
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/register
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-login
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/login
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 3
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-verify
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/verify-email,/api/v1/auth/resend-verification-code
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 30
                    redis-rate-limiter.burstCapacity: 50
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-password
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/forgot-password,/api/v1/auth/reset-password
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-refresh
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/refresh
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 30
                    redis-rate-limiter.burstCapacity: 50
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-logout
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/logout

            - id: auth-public
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/.well-known/**
            - id: auth-me
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/me
            # ========== TASK-SERVICE ==========
            - id: task-service
              uri: ${TASK_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/tasks/**


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    gateway:
      access: none
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG