dependencies {
    // =========================
    // Kafka (consumer)
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // =========================
    // Mail
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // =========================
    // Database (idempotency — processed events)
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    runtimeOnly 'org.postgresql:postgresql'

    // =========================
    // Monitoring / Actuator
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // =========================
    // MessageService
    // =========================
    implementation project(':common')

    // =========================
    // Tests
    // =========================
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation "org.testcontainers:testcontainers-kafka:2.0.5"
    testImplementation 'org.awaitility:awaitility'
}

