app:
  security:
    frontend-origin: "http://localhost:7777"
    oauth2-success-redirect: "http://localhost:7777/oauth/success"
    oauth2-failure-redirect: "http://localhost:7777/login?error=oauth"
    jwt:
      issuer: "myapp"
      secret: "${JWT_SECRET}"
      access-token-minutes: 15
      refresh-token-days: 7

spring:
  application:
    name: toDoApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email