dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    // =========================
    // Monitoring / Actuator
    // =========================
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'io.github.resilience4j:resilience4j-micrometer'

    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    implementation("org.springframework.boot:spring-boot-starter-aop:3.5.15")
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.testcontainers:testcontainers-kafka:2.0.5'
    testImplementation 'org.awaitility:awaitility'
}
