server:
  port: ${EMAIL_SENDER_PORT:8083}

spring:
  application:
    name: email-sender

  datasource:
    url: ${EMAIL_DATASOURCE_URL:jdbc:postgresql://localhost:5434/email_db}
    username: ${EMAIL_DATASOURCE_USERNAME:emailuser}
    password: ${EMAIL_DATASOURCE_PASSWORD:emailpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:email-sender}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  mail:
    from: ${MAIL_FROM:noreply@todoapp.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    ru.pancomanco.emailsender: DEBUG
    org.springframework.kafka: INFO