server:
  port: ${TASK_SERVICE_PORT:8082}

spring:
  application:
    name: task-service

  datasource:
    url: ${TASK_DATASOURCE_URL:jdbc:postgresql://localhost:5433/task_db}
    username: ${TASK_DATASOURCE_USERNAME:taskuser}
    password: ${TASK_DATASOURCE_PASSWORD:taskpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8081}/.well-known/jwks.json
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:600000}
      cache-null-values: false

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:toDoApplication}
  internal:
    api-key: ${INTERNAL_API_KEY:SECRET}
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ${HEALTH_DETAILS:never}

logging:
  level:
    root: WARN
    ru.pancomanco.taskservice: ${LOG_APP:INFO}
    org.springframework.security: ${LOG_SECURITY:WARN}
    org.springframework.web: ${LOG_WEB:WARN}
    org.hibernate.SQL: ${LOG_SQL:WARN}
    org.hibernate.orm.jdbc.bind: ${LOG_SQL_BIND:WARN}
    org.springframework.cache: ${LOG_CACHE:INFO}
    org.springframework.data.redis: ${LOG_REDIS:WARN}