server:
  port: 8082

spring:
  application:
    name: task-service

  datasource:
    url: ${TASK_DATASOURCE_URL:jdbc:postgresql://localhost:5433/task_db}
    username: ${TASK_DATASOURCE_USERNAME:taskuser}
    password: ${TASK_DATASOURCE_PASSWORD:taskpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8081}/.well-known/jwks.json}

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:toDoApplication}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    ru.pancomanco.taskservice: DEBUG
    org.springframework.security: INFO